import { GameEvent } from "./types";

const testEvents: GameEvent[] = [
  { key: "ship_added", shipId: "1", position: { x: 16, y: 11 } },
  { key: "ship_added", shipId: "2", position: { x: 7, y: 7 } },
  { key: "dust_spawned", dustId: "1", position: { x: 19, y: 3 }, direction: { x: -1, y: -1 } },
  { key: "new_turn", turnNumber: 1 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 19, y: 3 }, position: { x: 18, y: 2 } },
  { key: "dust_spawned", dustId: "2", position: { x: 5, y: 19 }, direction: { x: 1, y: -1 } },
  { key: "dust_spawned", dustId: "3", position: { x: 0, y: 9 }, direction: { x: 1, y: 0 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 16, y: 11 }, position: { x: 15, y: 11 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 7, y: 7 }, position: { x: 6, y: 8 } },
  { key: "new_turn", turnNumber: 2 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 18, y: 2 }, position: { x: 17, y: 1 } },
  { key: "dust_moved", dustId: "2", previousPosition: { x: 5, y: 19 }, position: { x: 6, y: 18 } },
  { key: "dust_moved", dustId: "3", previousPosition: { x: 0, y: 9 }, position: { x: 1, y: 9 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 15, y: 11 }, position: { x: 14, y: 11 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 6, y: 8 }, position: { x: 5, y: 9 } },
  { key: "new_turn", turnNumber: 3 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 17, y: 1 }, position: { x: 16, y: 0 } },
  { key: "dust_moved", dustId: "2", previousPosition: { x: 6, y: 18 }, position: { x: 7, y: 17 } },
  { key: "dust_moved", dustId: "3", previousPosition: { x: 1, y: 9 }, position: { x: 2, y: 9 } },
  { key: "dust_spawned", dustId: "4", position: { x: 0, y: 4 }, direction: { x: 1, y: -1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 14, y: 11 }, position: { x: 13, y: 11 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 5, y: 9 }, position: { x: 4, y: 9 } },
  { key: "new_turn", turnNumber: 4 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 16, y: 0 }, position: { x: 15, y: 1 } },
  { key: "dust_moved", dustId: "2", previousPosition: { x: 7, y: 17 }, position: { x: 8, y: 16 } },
  { key: "dust_moved", dustId: "3", previousPosition: { x: 2, y: 9 }, position: { x: 3, y: 9 } },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 0, y: 4 }, position: { x: 1, y: 3 } },
  { key: "dust_spawned", dustId: "5", position: { x: 4, y: 19 }, direction: { x: -1, y: -1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 13, y: 11 }, position: { x: 12, y: 12 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 4, y: 9 }, position: { x: 3, y: 9 } },
  { key: "dust_destroyed", dustId: "3", position: { x: 3, y: 9 } },
  { key: "score_changed", shipId: "2", score: 10 },
  { key: "new_turn", turnNumber: 5 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 15, y: 1 }, position: { x: 14, y: 2 } },
  { key: "dust_moved", dustId: "2", previousPosition: { x: 8, y: 16 }, position: { x: 9, y: 15 } },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 1, y: 3 }, position: { x: 2, y: 2 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 4, y: 19 }, position: { x: 3, y: 18 } },
  { key: "dust_spawned", dustId: "6", position: { x: 19, y: 15 }, direction: { x: -1, y: -1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 12, y: 12 }, position: { x: 11, y: 13 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 3, y: 9 }, position: { x: 4, y: 9 } },
  { key: "new_turn", turnNumber: 6 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 14, y: 2 }, position: { x: 13, y: 3 } },
  { key: "dust_moved", dustId: "2", previousPosition: { x: 9, y: 15 }, position: { x: 10, y: 14 } },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 2, y: 2 }, position: { x: 3, y: 1 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 3, y: 18 }, position: { x: 2, y: 17 } },
  { key: "dust_moved", dustId: "6", previousPosition: { x: 19, y: 15 }, position: { x: 18, y: 14 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 11, y: 13 }, position: { x: 10, y: 14 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 4, y: 9 }, position: { x: 5, y: 9 } },
  { key: "dust_destroyed", dustId: "2", position: { x: 10, y: 14 } },
  { key: "score_changed", shipId: "1", score: 10 },
  { key: "new_turn", turnNumber: 7 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 13, y: 3 }, position: { x: 12, y: 4 } },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 3, y: 1 }, position: { x: 4, y: 0 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 2, y: 17 }, position: { x: 1, y: 16 } },
  { key: "dust_moved", dustId: "6", previousPosition: { x: 18, y: 14 }, position: { x: 17, y: 13 } },
  { key: "dust_spawned", dustId: "7", position: { x: 19, y: 17 }, direction: { x: -1, y: 0 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 10, y: 14 }, position: { x: 11, y: 13 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 5, y: 9 }, position: { x: 6, y: 9 } },
  { key: "new_turn", turnNumber: 8 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 12, y: 4 }, position: { x: 11, y: 5 } },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 4, y: 0 }, position: { x: 5, y: 1 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 1, y: 16 }, position: { x: 0, y: 15 } },
  { key: "dust_moved", dustId: "6", previousPosition: { x: 17, y: 13 }, position: { x: 16, y: 12 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 19, y: 17 }, position: { x: 18, y: 17 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 11, y: 13 }, position: { x: 12, y: 12 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 6, y: 9 }, position: { x: 7, y: 9 } },
  { key: "new_turn", turnNumber: 9 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 11, y: 5 }, position: { x: 10, y: 6 } },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 5, y: 1 }, position: { x: 6, y: 2 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 0, y: 15 }, position: { x: 1, y: 14 } },
  { key: "dust_moved", dustId: "6", previousPosition: { x: 16, y: 12 }, position: { x: 15, y: 11 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 18, y: 17 }, position: { x: 17, y: 17 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 12, y: 12 }, position: { x: 13, y: 11 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 7, y: 9 }, position: { x: 8, y: 8 } },
  { key: "new_turn", turnNumber: 10 },
  { key: "dust_moved", dustId: "1", previousPosition: { x: 10, y: 6 }, position: { x: 9, y: 7 } },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 6, y: 2 }, position: { x: 7, y: 3 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 1, y: 14 }, position: { x: 2, y: 13 } },
  { key: "dust_moved", dustId: "6", previousPosition: { x: 15, y: 11 }, position: { x: 14, y: 10 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 17, y: 17 }, position: { x: 16, y: 17 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 13, y: 11 }, position: { x: 14, y: 10 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 8, y: 8 }, position: { x: 9, y: 7 } },
  { key: "dust_destroyed", dustId: "1", position: { x: 9, y: 7 } },
  { key: "score_changed", shipId: "1", score: 20 },
  { key: "dust_destroyed", dustId: "6", position: { x: 14, y: 10 } },
  { key: "score_changed", shipId: "2", score: 20 },
  { key: "new_turn", turnNumber: 11 },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 7, y: 3 }, position: { x: 8, y: 4 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 2, y: 13 }, position: { x: 3, y: 12 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 16, y: 17 }, position: { x: 15, y: 17 } },
  { key: "dust_spawned", dustId: "8", position: { x: 13, y: 0 }, direction: { x: 1, y: 1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 14, y: 10 }, position: { x: 13, y: 11 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 9, y: 7 }, position: { x: 9, y: 6 } },
  { key: "new_turn", turnNumber: 12 },
  { key: "dust_moved", dustId: "4", previousPosition: { x: 8, y: 4 }, position: { x: 9, y: 5 } },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 3, y: 12 }, position: { x: 4, y: 11 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 15, y: 17 }, position: { x: 14, y: 17 } },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 13, y: 0 }, position: { x: 14, y: 1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 13, y: 11 }, position: { x: 12, y: 12 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 9, y: 6 }, position: { x: 9, y: 5 } },
  { key: "dust_destroyed", dustId: "4", position: { x: 9, y: 5 } },
  { key: "score_changed", shipId: "2", score: 30 },
  { key: "new_turn", turnNumber: 13 },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 4, y: 11 }, position: { x: 5, y: 10 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 14, y: 17 }, position: { x: 13, y: 17 } },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 14, y: 1 }, position: { x: 15, y: 2 } },
  { key: "dust_spawned", dustId: "9", position: { x: 13, y: 19 }, direction: { x: 1, y: -1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 12, y: 12 }, position: { x: 11, y: 13 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 9, y: 5 }, position: { x: 8, y: 6 } },
  { key: "new_turn", turnNumber: 14 },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 5, y: 10 }, position: { x: 6, y: 9 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 13, y: 17 }, position: { x: 12, y: 17 } },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 15, y: 2 }, position: { x: 16, y: 3 } },
  { key: "dust_moved", dustId: "9", previousPosition: { x: 13, y: 19 }, position: { x: 14, y: 18 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 11, y: 13 }, position: { x: 10, y: 14 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 8, y: 6 }, position: { x: 8, y: 7 } },
  { key: "new_turn", turnNumber: 15 },
  { key: "dust_moved", dustId: "5", previousPosition: { x: 6, y: 9 }, position: { x: 7, y: 8 } },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 12, y: 17 }, position: { x: 11, y: 17 } },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 16, y: 3 }, position: { x: 17, y: 4 } },
  { key: "dust_moved", dustId: "9", previousPosition: { x: 14, y: 18 }, position: { x: 15, y: 17 } },
  { key: "dust_spawned", dustId: "10", position: { x: 0, y: 12 }, direction: { x: 1, y: 1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 10, y: 14 }, position: { x: 9, y: 15 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 8, y: 7 }, position: { x: 7, y: 8 } },
  { key: "dust_destroyed", dustId: "5", position: { x: 7, y: 8 } },
  { key: "score_changed", shipId: "2", score: 40 },
  { key: "new_turn", turnNumber: 16 },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 11, y: 17 }, position: { x: 10, y: 17 } },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 17, y: 4 }, position: { x: 18, y: 5 } },
  { key: "dust_moved", dustId: "9", previousPosition: { x: 15, y: 17 }, position: { x: 16, y: 16 } },
  { key: "dust_moved", dustId: "10", previousPosition: { x: 0, y: 12 }, position: { x: 1, y: 13 } },
  { key: "dust_spawned", dustId: "11", position: { x: 6, y: 0 }, direction: { x: -1, y: 1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 9, y: 15 }, position: { x: 9, y: 16 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 7, y: 8 }, position: { x: 6, y: 7 } },
  { key: "new_turn", turnNumber: 17 },
  { key: "dust_moved", dustId: "7", previousPosition: { x: 10, y: 17 }, position: { x: 9, y: 17 } },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 18, y: 5 }, position: { x: 19, y: 6 } },
  { key: "dust_moved", dustId: "9", previousPosition: { x: 16, y: 16 }, position: { x: 17, y: 15 } },
  { key: "dust_moved", dustId: "10", previousPosition: { x: 1, y: 13 }, position: { x: 2, y: 14 } },
  { key: "dust_moved", dustId: "11", previousPosition: { x: 6, y: 0 }, position: { x: 5, y: 1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 9, y: 16 }, position: { x: 9, y: 17 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 6, y: 7 }, position: { x: 5, y: 6 } },
  { key: "dust_destroyed", dustId: "7", position: { x: 9, y: 17 } },
  { key: "score_changed", shipId: "1", score: 30 },
  { key: "new_turn", turnNumber: 18 },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 19, y: 6 }, position: { x: 18, y: 7 } },
  { key: "dust_moved", dustId: "9", previousPosition: { x: 17, y: 15 }, position: { x: 18, y: 14 } },
  { key: "dust_moved", dustId: "10", previousPosition: { x: 2, y: 14 }, position: { x: 3, y: 15 } },
  { key: "dust_moved", dustId: "11", previousPosition: { x: 5, y: 1 }, position: { x: 4, y: 2 } },
  { key: "dust_spawned", dustId: "12", position: { x: 18, y: 0 }, direction: { x: 0, y: 1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 9, y: 17 }, position: { x: 8, y: 17 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 5, y: 6 }, position: { x: 4, y: 5 } },
  { key: "new_turn", turnNumber: 19 },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 18, y: 7 }, position: { x: 17, y: 8 } },
  { key: "dust_moved", dustId: "9", previousPosition: { x: 18, y: 14 }, position: { x: 19, y: 13 } },
  { key: "dust_moved", dustId: "10", previousPosition: { x: 3, y: 15 }, position: { x: 4, y: 16 } },
  { key: "dust_moved", dustId: "11", previousPosition: { x: 4, y: 2 }, position: { x: 3, y: 3 } },
  { key: "dust_moved", dustId: "12", previousPosition: { x: 18, y: 0 }, position: { x: 18, y: 1 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 8, y: 17 }, position: { x: 7, y: 17 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 4, y: 5 }, position: { x: 3, y: 4 } },
  { key: "new_turn", turnNumber: 20 },
  { key: "dust_moved", dustId: "8", previousPosition: { x: 17, y: 8 }, position: { x: 16, y: 9 } },
  { key: "dust_moved", dustId: "9", previousPosition: { x: 19, y: 13 }, position: { x: 18, y: 12 } },
  { key: "dust_moved", dustId: "10", previousPosition: { x: 4, y: 16 }, position: { x: 5, y: 17 } },
  { key: "dust_moved", dustId: "11", previousPosition: { x: 3, y: 3 }, position: { x: 2, y: 4 } },
  { key: "dust_moved", dustId: "12", previousPosition: { x: 18, y: 1 }, position: { x: 18, y: 2 } },
  { key: "ship_moved", shipId: "1", previousPosition: { x: 7, y: 17 }, position: { x: 6, y: 17 } },
  { key: "ship_moved", shipId: "2", previousPosition: { x: 3, y: 4 }, position: { x: 2, y: 4 } },
  { key: "dust_destroyed", dustId: "11", position: { x: 2, y: 4 } },
  { key: "score_changed", shipId: "2", score: 50 },
  { key: "game_finished" },
];

export default testEvents;
