const config = {
  RAND_ADDRESS: import.meta.env.STARKONQUEST_RAND_ADDRESS,
  BATTLE_ADDRESS: import.meta.env.STARKONQUEST_BATTLE_ADDRESS,
  DUST_ADDRESS: import.meta.env.STARKONQUEST_DUST_ADDRESS,
  SHIP_ADDRESS: import.meta.env.STARKONQUEST_SHIP_ADDRESS,

  PROVIDER_HOSTNAME: import.meta.env.STARKONQUEST_PROVIDER_HOSTNAME,
};

export default config;
